# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/schedulytics-278820/schedulytics-grpc-server
  tag: 4d7817fbb1aa2e478b7f78e7efd79109c14bdc40
  pullPolicy: IfNotPresent
service:
  name: schedulytics-server
  type: NodePort
  externalPort: 8010
  internalPort: 8010
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
database:
  host: mongodb
  port: 27017
  username: schedulytics
  password: sdgl354053fdks
